cat <<EOF > docker-compose.yml
version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./containers/app/Dockerfile
    environment:
      ### [Change: SecretForRDSAwsmaster > host]
      MYSQL_HOST: senobe-prod-rds.cluster-cfarhj6m4el8.ap-northeast-1.rds.amazonaws.com
      ### [Change: SecretForRDSAwsmaster > database]
      MYSQL_DATABASE: senobe
      ### [Change: SecretForRDSAwsmaster > username]
      MYSQL_USER: senobe
      ### [Change: SecretForRDSAwsmaster > password]
      MYSQL_PASSWORD: KP30M9dv9roYHqE5E9ieVWFwBQFXQ8wc
      ### No change
      RAILS_ENV: development
      ### [Change: Route 53 > HostedZone]
      RAILS_CONFIG_HOSTS: .senobe.cloud
    volumes:
      - ./app/:/awsmaster/
    ports:
      - "3000:3000"
    container_name: app
    restart: always
  web:
    build:
      context: .
      dockerfile: ./containers/web/Dockerfile
    command: /bin/bash -c "envsubst '\$\$NGINX_BACKEND' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    environment:
      NGINX_BACKEND: app
    volumes:
      - ./containers/web/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/web/default.conf.template:/etc/nginx/conf.d/default.conf.template
    ports:
      - "80:80"
    depends_on:
      - app
    container_name: web
    restart: always
EOF