---
### [Change Name] UserRubiconLink, rubicon.link
AWSTemplateFormatVersion: "2010-09-09"
Description: Create AWS IAM User etc.

Resources:
  ## IAM: Group
  GroupAdministrators:
    Type: AWS::IAM::Group
    Properties:
      GroupName: Administrators
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  ## IAM: User
  UserRubiconLink: ### [Change Name]
    Type: AWS::IAM::User
    Properties:
      UserName: rubicon.link ### [Change Name]
      LoginProfile:
        Password: 123456=NuFuA
        PasswordResetRequired: true
      Groups:
        - !Ref GroupAdministrators

Outputs:
  ## IAM: Group
  GroupAdministrators:
    Value: !GetAtt GroupAdministrators.Arn
    Export:
      Name: !Sub ${AWS::StackName}-GroupAdministrators

  ## IAM: User
  UserRubiconLink: ### [Change Name]
    Value: !GetAtt UserRubiconLink.Arn ### [Change Name]
    Export:
      Name: !Sub ${AWS::StackName}-UserRubiconLink ### [Change Name]